# Generated by Django 2.0.5 on 2018-12-18 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0003_remove_userprofileinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
