# Generated by Django 2.0.5 on 2018-12-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0004_auto_20181218_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='project_2_app.UserProfileInfo'),
        ),
    ]
