# Generated by Django 2.0.5 on 2018-12-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_app', '0006_auto_20181219_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(default='', max_length=4),
        ),
    ]
